project:
  type: website
  output-dir: docs

website:
  title: "Website thing"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mtran-code/informatics-site
    contents:
      - index.qmd
      - pages/about.qmd
      - section: "AI Projects in R"
        contents:
          - pages/linreg.qmd
          - pages/faces.qmd
          - pages/filters.qmd
      - section: "RNA-Seq Analysis"
        contents:
          - setup.qmd
  page-footer: "Michael Tran" 

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/styles.css
    toc: true
