project:
  type: website
  output-dir: docs

website:
  title: "Website for Informatics Projects"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mtran-code/informatics-site
    contents:
      - index.qmd
      - pages/about.qmd
      - section: "Basics (WIP)"
        contents:
          - Linear Algebra
          - ggplot2
      - section: "AI Projects in R"
        contents:
          - pages/regression.qmd
          - Eigenfaces (WIP)
          - Edge Detection (WIP)
      - section: "RNA-Seq Analysis (WIP)"
        contents:
          - Preprocessing and Alignment
          - Analysis
  page-footer: "Michael Tran" 

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/styles.css
    toc: true
